# Custom Language File for Launcher Customizer

[ejs.app]
title = "꼬예유&한예찬 시참서버 전용 런쳐"

[ejs.landing]
mediaInstagramURL = "https://www.instagram.com/koyeyu"
mediaYouTubeURL = "https://www.youtube.com/@%EA%BC%AC%EC%98%88%EC%9C%A0"
mediaDiscordURL = "https://discord.gg/dddRV5bkZa"

[ejs.settings]
sourceGithubLink = "https://github.com/koyeyuTeam/KoyeyuLauncher"
supportLink = "https://github.com/koyeyuTeam/KoyeyuLauncher/issues"

[ejs.welcome]
welcomeHeader = "시참 런쳐 실행을 위해, 몇가지 절차가 필요해요!"
welcomeDescription = "아래에 있는 버튼을 눌러, 본인의 마인크래프트 계정으로 로그인을 진행해주세요."
welcomeDescCTA = "(아마도) 몇 분 걸리지 않을거에요..! 해당 작업이 완료되어야, 시참 서버에 참여가 가능합니다."
