[ejs.landing]
updateAvailableTooltip = "업데이트가 가능해요!"
usernamePlaceholder = "유저 닉네임"
usernameEditButton = "수정"
settingsTooltip = "설정"
serverStatus = "서버"
serverStatusPlaceholder = "오프라인 (꺼짐)"
mojangStatus = "모장 상태"
mojangStatusTooltipTitle = "연결에 필요한 서버들"
newsButton = "소식들"
launchButton = "실행!"
launchButtonPlaceholder = "&#8226; 서버가 선택되지 않았어요."
launchDetails = "잠시만 기다려주세요..."
newsNavigationStatus = "{totalPages}중, {currentPage} 페이지."
newsErrorLoadSpan = "소식을 불러오는중..."
newsErrorFailedSpan = "소식을 불러오지 못했어요 :<"
newsErrorRetryButton = "다시 시도하기"
newsErrorNoneSpan = "소식 없음!"

[ejs.loginOptions]
loginOptionsTitle = "어떤 방법으로, 마인크래프트에 로그인하시겠어요?"
loginWithMicrosoft = "마이크로소프트 계정"
cancelButton = "취소"

[ejs.overlay]
serverSelectHeader = "접속 가능한 서버들"
serverSelectConfirm = "선택 완료"
serverSelectCancel = "취소"
accountSelectHeader = "서버에 접속할 계정 선택"
accountSelectConfirm = "선택 완료"
accountSelectCancel = "취소"

[ejs.settings]
navHeaderText = "설정"
navAccount = "계정 선택"
navMinecraft = "마인크래프트 설정"
navMods = "모드 설정"
navJava = "자바 설정"
navLauncher = "런쳐 설정"
navAbout = "런쳐 정보"
navUpdates = "런쳐 업데이트"
navDone = "완료"
tabAccountHeaderText = "계정 선택"
tabAccountHeaderDesc = "여기에서는, 새로운 마인크래프트 계정을 추가하거나, 삭제할 수 있어요."
microsoftAccount = "마이크로소프트"
addMicrosoftAccount = "+ 마이크로소프트 계정 추가하기"
minecraftTabHeaderText = "마인크래프트 설정"
minecraftTabHeaderDesc = "여기에서는, 마인크래프트 실행과 관련된 설정을 할 수 있어요."
gameResolutionTitle = "게임 시작할 때의 해상도"
launchFullscreenTitle = "전체 화면으로 실행하기."
autoConnectTitle = "게임을 실행할 때, 자동으로 시참 서버에 연결하기."
launchDetachedTitle = "런쳐와 게임을 분리하기."
launchDetachedDesc = "분리되지 않은 상태에서는, 런쳐를 종료하면 게임도 같이 종료됩니다."
tabModsHeaderText = "모드 설정"
tabModsHeaderDesc = "여기서는 모드를 활성화하거나, 비활성화 할 수 있어요."
switchServerButton = "서버 변경!"
requiredMods = "필수 모드들!"
optionalMods = "선택 가능한 모드들."
shaderpacks = "쉐이더팩 선택"
shaderpackDesc = "쉐이더를 활성화하거나, 비활성화할 수 있어요. 다만, 쉐이더를 사용할때는 게임이 부드럽게 돌아가지 않을 수 있으니 주의해주세요."
selectShaderpack = "쉐이더팩 선택"
tabJavaHeaderText = "자바 설정"
tabJavaHeaderDesc = "여기에서는, 자바 설정을 손볼 수 있어요. (전문가용!)"
memoryTitle = "메모리 설정"
maxRAM = "사용할 최대 메모리"
minRAM = "사용할 최소 메모리"
memoryDesc = "최소 3기가를 사용하는게 좋아요. 최대와 최소값을 같게 만들면, 랙이 더 줄어들수도 있어요."
memoryTotalTitle = "컴퓨터에는..."
memoryAvailableTitle = "지금 사용 가능한건..."
javaExecutableTitle = "자바 실행파일 선택하기"
javaExecSelDialogTitle = "자바 실행파일을 선택하세요."
javaExecSelButtonText = "파일 선택..."
javaExecDesc = "등록된 자바 실행파일은, 게임을 실행하기 전 검증이 진행됩니다."
javaPathDesc = "경로는 항상 <strong>{pathSuffix}</strong> 으로 끝나야해요."
jvmOptsTitle = "JVM 추가 설정"
jvmOptsDesc = "게임을 실행할 때, 들어갈 JVM 옵션이에요. <strong><em>-Xms</em>, <em>-Xmx</em> 은 포함되지 않아야해요.</strong>"
launcherTabHeaderText = "런쳐 설정"
launcherTabHeaderDesc = "여기에서는, 런쳐와 관련된 설정을 할 수 있어요."
allowPrereleaseTitle = "프리릴리즈 업데이트 허용하기."
allowPrereleaseDesc = "런쳐의 프리릴리즈 업데이트는 새로운 기능을 포함할 수 있지만, 테스트되지 않거나 버그가 있을 수 있어요.<br>이 옵션은 <strong>이미 프리릴리즈를 사용하고 있다면, 항상 켜져있어요.</strong>"
dataDirectoryTitle = "데이터 경로"
selectDataDirectory = "데이터 경로 선택"
chooseFolder = "폴더 선택..."
dataDirectoryDesc = "모든 게임 파일과, 자바 실행 파일은 해당 경로에 저장될거에요.<br>스크린샷과 싱글 월드는 다른 폴더에 저장됩니다 :>"
aboutTabHeaderText = "런쳐 정보"
aboutTabHeaderDesc = "여기에서는, 이 런쳐의 정보와 해당 버전의 업데이트 소식을 볼 수 있어요."
aboutTitle = "{appName}"
stableRelease = "(안정적인 버전)"
versionText = "버전 "
sourceGithub = "이 런쳐의 소스코드 (깃허브)"
originalSource = "원본 소스코드"
support = "버그 제보하기"
releaseNotes = "업데이트 소식"
changelog = "변경사항"
noReleaseNotes = "업데이트 소식이 없어요."
viewReleaseNotes = "깃허브에서 업데이트 소식 보기."
launcherUpdatesHeaderText = "런쳐 업데이트."
launcherUpdatesHeaderDesc = "런쳐의 업데이트를 다운로드하고, 설치하고, 확인할 수 있어요."
checkForUpdates = "업데이트 확인하기"
whatsNew = "이 버전에서 새로 추가된것!"
updateReleaseNotes = "업데이트 소식 새로고침"

[ejs.waiting]
waitingText = "마이크로소프트의 응답을 기다리는중.."

[ejs.welcome]
continueButton = "계속 진행하기"


[js.discord]
waiting = "디스코드 클라이언트를 기다리고있어요.."
state = "서버: {shortId}"

[js.index]
microsoftLoginTitle = "마이크로소프트 로그인"
microsoftLogoutTitle = "마이크로소프트 로그아웃"

[js.login]
login = "로그인"
loggingIn = "로그인중..."
success = "성공"
tryAgain = "다시 시도하기"

[js.landing.launch]
pleaseWait = "잠시만 기다려주세요.."
failureTitle = "실행 도중, 오류가 발생했어요."
failureText = "콘솔 (CTRL + Shift + i) 에서 자세한 내용을 확인해주세요."
okay = "네. 확인했습니다."

[js.landing.selectedAccount]
noAccountSelected = "아무 계정도 선택되지 않음!"

[js.landing.selectedServer]
noSelection = "아무 서버도 선택되지 않음!"
loading = "로딩중..."

[js.landing.serverStatus]
server = "서버"
offline = "오프라인"
players = "플레이어"

[js.landing.systemScan]
checking = "시스템 정보를 확인하는중..."
noCompatibleJava = "호환되는 자바 실행 파일이 감지되지 않았어요."
installJavaMessage = "마인크래프트의 실행을 위해서는, 64비트의 자바 {major} 버전 설치가 필요해요. 지금 설치할까요?"
installJava = "네. 자바를 설치해주세요 :>"
installJavaManually = "아니요! 제가 직접 설치할게요!"
javaDownloadPrepare = "자바 다운로드 준비중..."
javaDownloadFailureTitle = "자바 다운로드 중, 오류가 발생했어요."
javaDownloadFailureText = "자바 다운로드에 실패했어요. 자세한 내용은 콘솔 (CTRL + Shift + i) 를 확인해주세요."
javaRequired = "실행하기 위해서는 자바가 필요합니다."
javaRequiredMessage = '실행을 위해선, 유효한 64비트 자바 {major} 버전이 필요해요.'
javaRequiredDismiss = "네. 이해했어요."
javaRequiredCancel = "뒤로 돌아가기"

[js.landing.downloadJava]
findJdkFailure = "OpenJDK 정보를 확인하지 못했어요."
javaDownloadCorruptedError = "다운로드 받은 자바 파일이 손상되었거나, 파일이 일치하지 않아요."
extractingJava = "자바의 압축을 해제하고 있어요..."
javaInstalled = "자바 설치 완료!"

[js.landing.dlAsync]
loadingServerInfo = "서버의 정보를 불러오는중..."
fatalError = "심각한 오류!"
unableToLoadDistributionIndex = "서버의 정보를 가져오지 못했어요... 인터넷 연결을 확인하고, 다시 실행해주세요."
pleaseWait = "잠시만 기다려주세요..."
errorDuringLaunchTitle = "런쳐를 실행중, 오류가 발생했어요."
seeConsoleForDetails = "자세한 내용은 콘솔 (CTRL + Shift + i) 를 확인해주세요."
validatingFileIntegrity = "파일 유효성 검사 진행중..."
errorDuringFileVerificationTitle = "파일의 유효성 검사를 진행하는 도중, 오류가 발생했어요."
downloadingFiles = "파일을 다운로드하는중..."
errorDuringFileDownloadTitle = "파일 다운로드 중, 오류가 발생했어요."
preparingToLaunch = "게임을 실행하기 전, 마지막 확인중..."
launchingGame = "게임 실행중..."
launchWrapperNotDownloaded = "게임을 실행하기 위한 메인 파일을 불러오지 못했어요... 아마도 바이러스로 분류된 것 같아요. 이 오류를 해결하기 위해선, 일시적으로 백신 프로그램을 끄고, 다시 실행해주세요."
doneEnjoyServer = "완료. 재밌게 플레이하세요 :>"
checkConsoleForDetails = "자세한 내용은 콘솔 (CTRL + Shift + i) 를 확인해주세요."

[js.landing.news]
checking = "새로운 소식이 있나 살펴보는중..."

[js.landing.discord]
loading = "게임을 불러오는중..."
joining = "꼬예유&한예찬 시참 서버에 참여하는중..."
joined = "꼬예유&한예찬 시참 서버에 참여 완료 :>"

[js.overlay]
dismiss = "취소"

[js.settings.fileSelectors]
executables = "실행 가능한 파일들"
allFiles = "모든 파일들"

[js.settings.mstfLogin]
errorTitle = "엇. 무언가 잘못되었어요..."
errorMessage = "마이크로소프트 인증에 실패했어요. 나중에 다시 시도해주세요."
okButton = "네. 확인했어요 :>"

[js.settings.mstfLogout]
errorTitle = "엇. 무언가 잘못되었어요..."
errorMessage = "마이크로소프트 로그아웃에 실패했어요. 나중에 다시 시도해주세요."
okButton = "네. 확인했어요 :>"

[js.settings.authAccountSelect]
selectButton = "계정 선택하기"
selectedButton = "선택된 계정 &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "주의!<br>이건 이 런쳐에 로그인된 마지막 계정이에요."
lastAccountWarningMessage = "런쳐를 이용하기 위해선, 최소 한개의 계정이 로그인되어있어야해요...<br><br><strong>정말로 로그아웃하시겠어요</strong>"
confirmButton = "네. 로그아웃하겠습니다."
cancelButton = "아니요."

[js.settings.authAccountPopulate]
username = "유저 닉네임"
uuid = "UUID"
selectAccount = "계정 선택하기"
selectedAccount = "계정 선택됨 ✓"
logout = "로그아웃"

[js.settings.serverListing]
mainServer = "메인서버"

[js.settings.java]
selectedJava = "자바 {version} ({vendor}) 가 선택되었어요."
invalidSelection = "유효하지 않은 파일이에요."
requiresJava = "64비트의 자바 {major} 버전이 필요해요."
availableOptions = "사용 가능한 옵션 보기. (HotSpot VM의 자바 {major} 버전 기준.)"

[js.settings.about]
preReleaseTitle = "프리릴리즈"
stableReleaseTitle = "안정적인 버전"
releaseNotesFailed = "업데이트 소식을 불러오지 못했어요."

[js.settings.updates]
newReleaseTitle = "새로운 업데이트가 존재해요."
newPreReleaseTitle = "새로운 프리릴리즈가 존재해요."
downloadingButton = "다운로드중..."
downloadButton = 'GitHub에서 다운로드가 진행되고 있어요. <span style="font-size: 10px;color: gray;text-shadow: none !important;">런쳐를 닫고, .dmg 파일을 실행해주세요.</span>'
latestVersionTitle = "이미 최신버전의 런쳐를 사용중이에요."
checkForUpdatesButton = "업데이트 확인하기"
checkingForUpdatesButton = "업데이트를 확인하는중..."

[js.settings.msftLogin]
errorTitle = "마이크로소프트 로그인에 실패했어요."
errorMessage = "로그인을 시도한 마이크로소프트 계정을 인증할 수 없어요. 나중에 다시 시도해주세요."
okButton = "네. 알겠습니다 :>"

[js.uibinder.startup]
fatalErrorTitle = "심각한 오류: 서버의 정보를 불러오지 못했어요."
fatalErrorMessage = "서버의 정보를 불러오지 못했어요. 인터넷 연결을 확인하고, 다시 실행해주세요."
closeButton = "닫기."

[js.uibinder.validateAccount]
failedMessageTitle = "계정 갱신 실패"
failedMessage = "<strong>{account}</strong> 계정을 갱신하던 도중, 문제가 발생했어요. 다른 계정을 선택하거나, 다시 로그인해주세요."
failedMessageSelectAnotherAccount = "<strong>{account}</strong> 계정을 갱신하던 도중, 문제가 발생했어요. 다시 로그인해주세요."
loginButton = "로그인"
selectAnotherAccountButton = "다른 계정 선택"

[js.uicore.autoUpdate]
checkingForUpdateButton = "업데이트를 확인하는 중..."
installNowButton = "지금 설치하기"
checkForUpdatesButton = "업데이트 확인하기"

[js.auth.microsoft.error]
noProfileTitle = "로그인 실패.<br>계정이 설정되지 않음."
noProfileDesc = "이 계정은 아직 마인크래프트 프로필이 설정되어있지 않아요.<br><br>만약, 최근에 게임을 구매했거나 Xbox Game Pass를 이용중이라면, <a href=\"https://minecraft.net/\">여기</a>에서 계정을 설정해주세요."
noXboxAccountTitle = "로그인 실패.<br>Xbox 계정이 아님."
noXboxAccountDesc = "이 계정은 Xbox 계정이 설정되어있지 않아요."
xblBannedTitle = "로그인 실패.<br>Xbox Live에 접근할 수 없음."
xblBannedDesc = "이 계정은 Xbox Live에 접근할 수 없는 국가에서 만들어진 계정이거나, 차단된 계정일 수 있어요."
under18Title = "로그인 실패.<br>미성년자 계정."
under18Desc = "18세 미만의 사용자 계정인 것 같아요.<br>이런 경우, 해당 계정을 성인이 가족 계정에 추가해야 플레이가 가능해요."
unknownTitle = "로그인 실패.<br>알 수 없음."
unknownDesc = "알 수 없는 오류가 발생했어요."
